### ISSUE TITLE
Error: The requested module '/_nuxt/node_modules/axios/index.js?v=64f0f6da' does not provide an export named 'default'

### ISSUE THREAD

**Issue by steffenr** [patrickcate/nuxt-jsonapi#142]
I created a simple nuxt3 application and try to replace the default useLazyFetch calls to a JSON:API via nuxt-jsonapi. 
But after adding the package via yarn (as described in the README) i get the following error in my applicaiton.  

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/axios/index.js?v=64f0f6da' does not provide an export named 'default'`

The log provided by the yarn dev command looks fine and is showing my configured baseURL for nuxt-jsonapi.

**Comment by palachX** [comment]
Same problem...

**Comment by patrickcate** [comment]
Thanks for creating the issue. I haven't been able to reproduce the error you both mentioned with a fresh Nuxt 3 app created with `nuxi`. Would you be able to create a minimal reproducible repo to help debug further?

**Comment by stekosto** [comment]
Same here

**Comment by patrickcate** [comment]
Might be a known issue with Nuxt and Vite: https://vite.nuxtjs.org/misc/common-issues/#uncaught-syntaxerror-the-requested-module--does-not-provide-an-export-named-default

You might try adding the following to your `nuxt.config.{t|j}s` file:
```
vite: {
  optimizeDeps: {
    exclude: ['axios']
  }
}
```

As I mentioned earlier I'll need a minimal reproducible repo or at least a public repo with the issue to debug further.

**Comment by stekosto** [comment]
> vite: {
>   optimizeDeps: {
>     exclude: ['axios']
>   }

This does not work, same error.  Also I try to use your playground but a lot of problems, too. 
First got ​          GET http://localhost:3000/ 500 (Internal Server Error)
I disable ssr and I am getting http://localhost:9999/jsonapi/article net::ERR_CONNECTION_REFUSED

**Comment by patrickcate** [comment]
I just published version `2.0.1` to npm. Please update to that version and see if it resolves the issue.

**Comment by stekosto** [comment]
> I just published version `2.0.1` to npm. Please update to that version and see if it resolves the issue.

Yes it does. Thanks

**Comment by palachX** [comment]
I use 2.0.1 and i have error

code: "ERR_BAD_OPTION_VALUE"
message:"options must be an object"
name: "AxiosError"


When i use

vite: {
  optimizeDeps: {
    exclude: ['axios']
  }
}

I have error:
The requested module '/_nuxt/node_modules/.vite/deps/axios.js?v=d62045e9' does not provide an export named 'default'

**Comment by patrickcate** [comment]
@palachX try removing the:
```
vite: {
  optimizeDeps: {
    exclude: ['axios']
  }
}
```
code. You should no need it with 2.0.1. If you still have the error, are you using Axios elsewhere in your app? If so can you confirm the version number?

**Comment by patrickcate** [comment]
Closing this issue. Please comment or re-open if this is still an issue.
