### ISSUE TITLE
Typings in VS Code

### ISSUE THREAD

**Issue by riddla** [patrickcate/nuxt-jsonapi#259]
Can you give me any hint, why the Typings in VS Code might not show up?

Using `const { $jsonApi } = useNuxtApp()` the IDE thinks that `const $jsonApi: unknown`.

Thanks a a lot for your great plugin :)

**Comment by patrickcate** [comment]
@riddla unfortunately I don't. When I open the repo in VSCode I get the correct typing.

![Screen Shot 2023-05-24 at 3 57 14 PM](https://github.com/patrickcate/nuxt-jsonapi/assets/6277206/67b5ab5c-8125-4eb7-973e-a139e9975013)

Do you have the [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) and [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) extensions installed and setup?

Is there a repo with the issue you can share?

**Comment by riddla** [comment]
@patrickcate, never mind – I found out that the project in question currently has no typing at all via `useNuxtApp`. So there must be another problem.

(I'll keep you posted when I find the underlying issue.)

**Comment by DanHulton** [comment]
Did you ever figure out why the project has no typings?  I'm running into the same issue (though I'm using Webstorm), and would love to have the proper types exposed to work with!

**Comment by DanHulton** [comment]
I opened a new issue about this, since it still seems to be relevant, along with a workaround that I'm using for now.
