### ISSUE TITLE
Same origin policy breaking requests

### ISSUE THREAD

**Issue by Minecodes** [patrickcate/nuxt-jsonapi#445]
![image](https://github.com/patrickcate/nuxt-jsonapi/assets/65566012/c94aa987-6e19-494b-b617-953a974482cd)
I'm currently trying to bypass this because I'm currently developing my site, and I don't if it will come up when the site is in production.
The URL I'm trying to request is my headless CMS/blogging software (e.g. blog.example.com), and the site is currently running on localhost but is going to be running on my webserver (e.g. example.com). Is this problem going to come up when it's on the web server, or is it only going to come up while I'm in development?
Also, if there is a bypass for the same origin policy then I would be thankful if you help me with that.

**Comment by patrickcate** [comment]
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) needs to be configured at the server level.  I would suggest searching for documentation or other resource for your specific server or host.

CORS and the error isn't related to this module.
